$SCRIPT:PRLS_COL_WIDTH_PRSP_name = 10;
$SCRIPT:PRLS_COL_WIDTH_PRSP_datatype = 10;
$SCRIPT:PRLS_COL_WIDTH_PRSP_tag_open = 45;
$SCRIPT:PRLS_COL_WIDTH_SNIFFED_tag_open = 10;
$SCRIPT:PRLS_COL_WIDTH_SNIFFED_data_value = 200;

Function SNIFFED_TAG_OPEN 
{
    return "<SNIFFED>"
}