[string]$SCRIPT:DIRECTORY_PATH_OF_pratom_ATOM_NUCLEUS = $PSScriptRoot
[string]$SCRIPT:DIRECTORY_PATH_OF_pratom_ATOM_NUCLEUS_NEUTRONS= "$($SCRIPT:DIRECTORY_PATH_OF_pratom_ATOM_NUCLEUS)\NEUTRONS\"
[string]$SCRIPT:DIRECTORY_PATH_OF_pratom_ATOM_NUCLEUS_PROTONS= "$($SCRIPT:DIRECTORY_PATH_OF_pratom_ATOM_NUCLEUS)\PROTONS\"